#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# Asclepias Broker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

# Clean redis
pipenv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
pipenv run invenio db destroy --yes-i-know
pipenv run invenio db init create
pipenv run invenio index destroy --force --yes-i-know
#pipenv run invenio index delete relationships
pipenv run invenio index create relationships -b asclepias_broker/mappings/os-v2/relationships/v1.0.0.json
#pipenv run invenio index init --force
pipenv run invenio queues delete
pipenv run invenio queues declare # asclepias_harvester_queues
